// <auto-generated />
using System;
using Karooooo.DriverPlanning.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Karooooo.DriverPlanning.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250326102704_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverAddressId")
                        .HasColumnType("int");

                    b.Property<int>("DriverBankingDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("DriverDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("DriverIdentificationId")
                        .HasColumnType("int");

                    b.Property<int>("DriverLisenceId")
                        .HasColumnType("int");

                    b.Property<int>("DriverNextOfKinId")
                        .HasColumnType("int");

                    b.Property<int>("DriverVehcileId")
                        .HasColumnType("int");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverAddressId")
                        .IsUnique();

                    b.HasIndex("DriverBankingDetailsId")
                        .IsUnique();

                    b.HasIndex("DriverDetailsId")
                        .IsUnique();

                    b.HasIndex("DriverIdentificationId")
                        .IsUnique();

                    b.HasIndex("DriverLisenceId")
                        .IsUnique();

                    b.HasIndex("DriverNextOfKinId")
                        .IsUnique();

                    b.HasIndex("DriverVehcileId")
                        .IsUnique();

                    b.HasIndex(new[] { "Uid" }, "UC_Driver_UID")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "UC_Driver_UserId")
                        .IsUnique();

                    b.ToTable("Driver", (string)null);
                });

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.DriverAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormattedAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProofOfAddressUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DriverAddressDetils");
                });

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.DriverBankingDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProofOfBankingDetailsUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DriverBankingDetails");
                });

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.DriverDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DriverIdentificationId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DriverIdentificationId");

                    b.ToTable("DriverDetails", (string)null);
                });

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.DriverIdentification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverIdentificationUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverWorkPermitUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentityType")
                        .HasColumnType("int");

                    b.Property<bool>("IsForeignNational")
                        .HasColumnType("bit");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidencyId")
                        .HasColumnType("int");

                    b.Property<int>("WorkPermit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResidencyId");

                    b.ToTable("DriverIdentificationDetails");
                });

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.DriverLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LicenceCode")
                        .HasColumnType("int");

                    b.Property<string>("LicenseDocumentImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LicenseType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DriverLicenseDetails");
                });

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.DriverNextOfKin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DriverNextOfKinDetails");
                });

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.DriverVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverVehicleLicenseId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleBackImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleColour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleFrontImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleSideImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DriverVehicleLicenseId");

                    b.ToTable("DriverVehicleDetails");
                });

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.DriverVehicleLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseDocumentImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleEngineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleRegisterNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DriverVehicleLicenseDetails");
                });

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.Nationality", b =>
                {
                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.Residency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResidencyDocumentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidencyStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ResidencyDetails");
                });

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.Driver", b =>
                {
                    b.HasOne("Karooooo.DriverPlanning.Domain.Entities.DriverAddress", "DriverAddress")
                        .WithOne()
                        .HasForeignKey("Karooooo.DriverPlanning.Domain.Entities.Driver", "DriverAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Karooooo.DriverPlanning.Domain.Entities.DriverBankingDetails", "DriverBankingDetails")
                        .WithOne()
                        .HasForeignKey("Karooooo.DriverPlanning.Domain.Entities.Driver", "DriverBankingDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Karooooo.DriverPlanning.Domain.Entities.DriverDetails", "DriverDetails")
                        .WithOne()
                        .HasForeignKey("Karooooo.DriverPlanning.Domain.Entities.Driver", "DriverDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Karooooo.DriverPlanning.Domain.Entities.DriverIdentification", "DriverIdentification")
                        .WithOne()
                        .HasForeignKey("Karooooo.DriverPlanning.Domain.Entities.Driver", "DriverIdentificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Karooooo.DriverPlanning.Domain.Entities.DriverLicense", "DriverLicense")
                        .WithOne()
                        .HasForeignKey("Karooooo.DriverPlanning.Domain.Entities.Driver", "DriverLisenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Karooooo.DriverPlanning.Domain.Entities.DriverNextOfKin", "NextOfKin")
                        .WithOne()
                        .HasForeignKey("Karooooo.DriverPlanning.Domain.Entities.Driver", "DriverNextOfKinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Karooooo.DriverPlanning.Domain.Entities.DriverVehicle", "DriverVehicle")
                        .WithOne()
                        .HasForeignKey("Karooooo.DriverPlanning.Domain.Entities.Driver", "DriverVehcileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverAddress");

                    b.Navigation("DriverBankingDetails");

                    b.Navigation("DriverDetails");

                    b.Navigation("DriverIdentification");

                    b.Navigation("DriverLicense");

                    b.Navigation("DriverVehicle");

                    b.Navigation("NextOfKin");
                });

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.DriverDetails", b =>
                {
                    b.HasOne("Karooooo.DriverPlanning.Domain.Entities.DriverIdentification", "DriverIdentification")
                        .WithMany()
                        .HasForeignKey("DriverIdentificationId");

                    b.Navigation("DriverIdentification");
                });

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.DriverIdentification", b =>
                {
                    b.HasOne("Karooooo.DriverPlanning.Domain.Entities.Residency", "Residency")
                        .WithMany()
                        .HasForeignKey("ResidencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residency");
                });

            modelBuilder.Entity("Karooooo.DriverPlanning.Domain.Entities.DriverVehicle", b =>
                {
                    b.HasOne("Karooooo.DriverPlanning.Domain.Entities.DriverVehicleLicense", "DriverVehicleLicense")
                        .WithMany()
                        .HasForeignKey("DriverVehicleLicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverVehicleLicense");
                });
#pragma warning restore 612, 618
        }
    }
}
